# Generated by Django 5.2.7 on 2025-10-19 15:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('battery_wh', models.IntegerField(blank=True, null=True)),
                ('motor_w', models.IntegerField(blank=True, null=True)),
                ('range_km_estimated', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bicycle_models',
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=128, unique=True)),
                ('gps_tracker_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('RENTED', 'Rented'), ('IN_REPAIR', 'In Repair'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=16)),
                ('current_battery_pct', models.SmallIntegerField(default=100)),
                ('mileage_km', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycles', to='bikes_manager.bicyclemodel')),
            ],
            options={
                'db_table': 'bicycles',
            },
        ),
    ]
