# Generated by Django 5.2.7 on 2025-10-22 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bicycle',
            options={'verbose_name': 'Велосипед', 'verbose_name_plural': 'Велосипеды'},
        ),
        migrations.AlterModelOptions(
            name='bicyclemodel',
            options={'verbose_name': 'Модель велосипеда', 'verbose_name_plural': 'Модели велосипедов'},
        ),
        migrations.RemoveField(
            model_name='bicycle',
            name='mileage_km',
        ),
        migrations.AddField(
            model_name='bicycle',
            name='production_year',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Год производства'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='current_battery_pct',
            field=models.SmallIntegerField(default=100, verbose_name='Износ батареи (%)'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='gps_tracker_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ID-трекера GPS'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='last_maintenance_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней ТО'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='last_status_change',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее изменение статуса'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycles', to='bikes_manager.bicyclemodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='serial_number',
            field=models.CharField(max_length=128, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Доступен'), ('RESERVED', 'Забронирован'), ('RENTED', 'Арендован'), ('IN_REPAIR', 'В ремонте'), ('DECOMMISSIONED', 'Выведен из эксплуатации')], default='AVAILABLE', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='battery_wh',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность батареи (Вт/ч)'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='manufacturer',
            field=models.CharField(max_length=255, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='model_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='Код модели'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='motor_w',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность велосипеда (Вт)'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название модели'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='range_km_estimated',
            field=models.IntegerField(blank=True, null=True, verbose_name='Запас хода (км)'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Вес велосипеда (кг)'),
        ),
    ]
