# Generated by Django 5.2.7 on 2025-10-23 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0002_alter_bicycle_options_alter_bicyclemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bikes', verbose_name='Фотография велосипеда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycles_model_photos', to='bikes_manager.bicyclemodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Фотография велосипеда',
                'verbose_name_plural': 'Фотографии велосипеда',
                'db_table': 'bicycles_model_photos',
            },
        ),
    ]
