# Generated by Django 5.2.7 on 2025-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0003_bicyclemodelphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicyclemodelphoto',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='bikes_model_photos', verbose_name='Фотография велосипеда'),
        ),
    ]
