# Generated by Django 5.2.7 on 2025-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0004_alter_bicyclemodelphoto_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='last_maintenance_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней ТО'),
        ),
    ]
