# Generated by Django 5.2.7 on 2025-10-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0005_alter_bicycle_last_maintenance_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='gps_tracker_id',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='ID-трекера GPS'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='serial_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='bicyclemodel',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Вес велосипеда (кг)'),
        ),
    ]
