# Generated by Django 5.2.7 on 2025-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0006_alter_bicycle_gps_tracker_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='current_battery_pct',
            field=models.SmallIntegerField(blank=True, default=100, null=True, verbose_name='Износ батареи (%)'),
        ),
    ]
