# Generated by Django 5.2.7 on 2025-10-20 17:07

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0002_alter_user_managers_adminuser_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31, unique=True),
        ),
    ]
