# Generated by Django 5.2.7 on 2025-10-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0004_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
