# Generated by Django 5.2.7 on 2025-10-22 17:34

import django.db.models.deletion
import phone_field.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0005_delete_usergroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='notificationtemplate',
            options={'verbose_name': 'Шаблон уведомлений', 'verbose_name_plural': 'Шаблоны уведомлений'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='trustedcontact',
            options={'verbose_name': 'Доверенное лицо', 'verbose_name_plural': 'Доверенные лица'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='correlation_id',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='subject_template',
        ),
        migrations.RemoveField(
            model_name='trustedcontact',
            name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, choices=[('ALMATY', 'Алматы')], default='ALMATY', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Права доступа'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('OPERATOR', 'Operator'), ('SUPPORT', 'Support'), ('MAINTENANCE', 'Maintenance')], max_length=32, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='admin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_manager.adminuser', verbose_name='Адмнинистратор'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('NOTIFICATION', 'Отправка уведомления'), ('AUDIT', 'Аудит'), ('SYSTEM', 'Система'), ('PAYMENT', 'оплата'), ('GEOZONE', 'Гео Зона'), ('OTHER', 'Другое')], max_length=64, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата-время'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='severity',
            field=models.CharField(default='INFO', max_length=16, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(verbose_name='Шаблон сообщения'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push'), ('SMS', 'SMS')], max_length=16, verbose_name='Канал связи'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя шаблона'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='placeholders',
            field=models.JSONField(default=dict, verbose_name='Заголовок сообщения'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='documents',
            field=models.JSONField(blank=True, default=dict, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], default='MALE', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_locale',
            field=models.CharField(blank=True, max_length=8, verbose_name='Предпочитаемый язык'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя доверенного лица'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='phone',
            field=phone_field.models.PhoneField(help_text='В международной форме', max_length=31, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_contacts', to='platform_manager.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='trustedcontact',
            name='relation',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'Супруг(а)'), ('SIBLING', 'Брат/Сестра'), ('PARENT', 'Родитель'), ('OTHER', 'Другое')], verbose_name='Кем приходится'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Номер телефона указывается в междной форме', max_length=31, unique=True, verbose_name='Номер телефона'),
        ),
    ]
