# Generated by Django 5.2.7 on 2025-10-23 14:55

import phone_field.models
import platform_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to=platform_manager.models.profile_id_image_upload_path, verbose_name='Фотография удостоверения (задняя сторона)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to=platform_manager.models.profile_id_image_upload_path, verbose_name='Фотография удостоверения (лицевая сторона)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default=1, max_length=40, verbose_name='Номер удостоверения личности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id_outstand',
            field=models.CharField(default=1, max_length=255, verbose_name='Кем выдано удостоверение личности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='manager_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(default=1, help_text='Номер телефона указывается в международной форме', max_length=31, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес прописки'),
        ),
        migrations.AddField(
            model_name='profile',
            name='relation',
            field=models.CharField(blank=True, choices=[('SPOUSE', 'Супруг(а)'), ('SIBLING', 'Брат/Сестра'), ('PARENT', 'Родитель'), ('OTHER', 'Другое')], verbose_name='Кем приходится'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='profile',
            name='trusted_contact_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Имя доверенного лица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='trusted_contact_phone',
            field=phone_field.models.PhoneField(default=1, help_text='Номер телефона указывается в международной форме', max_length=31, verbose_name='Номер телефона доверенного лица'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_face_photo',
            field=models.ImageField(blank=True, null=True, upload_to=platform_manager.models.profile_face_image_upload_path, verbose_name='Фотография пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_locale',
            field=models.CharField(blank=True, choices=[('RUS', 'Русский'), ('KAZ', 'Казахский'), ('ENG', 'Английский'), ('UZB', 'Узбекский'), ('KRG', 'Киргизкий'), ('OTHER', 'Другой')], default='RUS', max_length=8, verbose_name='Предпочитаемый язык'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Номер телефона указывается в международной форме', max_length=31, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.DeleteModel(
            name='TrustedContact',
        ),
    ]
