# Generated by Django 5.2.7 on 2025-10-23 15:52

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона указывается в международной форме', max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trusted_contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона указывается в международной форме', max_length=128, region=None, verbose_name='Номер телефона доверенного лица'),
        ),
    ]
