# Generated by Django 5.2.7 on 2025-11-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0013_formresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formresponse',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='formresponse',
            name='last_name',
        ),
        migrations.AddField(
            model_name='formresponse',
            name='criminal_offenses',
            field=models.TextField(blank=True, verbose_name='За какие преступления'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='criminal_period_where',
            field=models.TextField(blank=True, verbose_name='Период и место отбытия наказания'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='criminal_record',
            field=models.BooleanField(default=False, verbose_name='Имеете ли судимость'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='denomination',
            field=models.CharField(blank=True, max_length=255, verbose_name='Мазхаб/религиозные взгляды'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='deportation_details',
            field=models.TextField(blank=True, verbose_name='Когда и причины депортации'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='deported',
            field=models.BooleanField(default=False, verbose_name='Депортировали/выдворяли ли вас'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='detained_abroad',
            field=models.BooleanField(default=False, verbose_name='Задерживались ли правоохранительными органами иностранного государства'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='detained_when_why',
            field=models.TextField(blank=True, verbose_name='Когда и по какой причине задерживали'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='detained_where',
            field=models.TextField(blank=True, verbose_name='Где содержали'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='full_name_and_birth',
            field=models.TextField(blank=True, verbose_name='ФИО, дата и место рождения'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='last_time_in_homeland',
            field=models.CharField(blank=True, max_length=255, verbose_name='Когда в последний раз были на родине'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='military_details',
            field=models.TextField(blank=True, verbose_name='Детали службы (страна/войска)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='military_service',
            field=models.BooleanField(default=False, verbose_name='Проходили ли службу в ВС'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='name_change_reason',
            field=models.TextField(blank=True, verbose_name='Причина изменения имени'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='name_changed',
            field=models.BooleanField(default=False, verbose_name='Изменяли ли имя/фамилию/отчество'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='not_allowed_reason',
            field=models.TextField(blank=True, verbose_name='Причина не пропуска в пункт назначения'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='phones_emails',
            field=models.TextField(blank=True, verbose_name='Номера телефонов и email'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_details',
            field=models.TextField(blank=True, verbose_name='Детали (ФИО, когда выехали, чем занимаются)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_in_countries',
            field=models.BooleanField(default=False, verbose_name='Есть ли родственники/знакомые в указанных странах'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_wanted',
            field=models.BooleanField(default=False, verbose_name='Разыскивается ли кто-нибудь из родственников'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_wanted_reason',
            field=models.TextField(blank=True, verbose_name='Причина розыска'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='religious',
            field=models.BooleanField(default=False, verbose_name='Религиозны ли вы'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visited_countries',
            field=models.BooleanField(default=False, verbose_name='Посещали ли указанные страны'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visited_countries_details',
            field=models.TextField(blank=True, verbose_name='Детали визитов (когда, цель, срок)'),
        ),
    ]
