# Generated by Django 5.2.9 on 2025-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0014_remove_formresponse_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='threat_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='Уровень опасности'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Общий балл'),
        ),
    ]
