# Generated by Django 5.2.9 on 2025-12-02 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0015_formresponse_threat_level_formresponse_total_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorderOfficerAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('radical_internet', models.BooleanField(default=False, verbose_name='1. Состоит в радикальных интернет-сообществах')),
                ('radical_internet_details', models.TextField(blank=True, verbose_name='Детали')),
                ('radical_religious_ideology', models.BooleanField(default=False, verbose_name='2. Является сторонником радикальных религиозных течений')),
                ('radical_religious_details', models.TextField(blank=True, verbose_name='Детали')),
                ('document_issues', models.BooleanField(default=False, verbose_name='3. Признаки в документах (депортация, запрет въезда)')),
                ('document_issues_details', models.TextField(blank=True, verbose_name='Детали')),
                ('religious_deviations', models.BooleanField(default=False, verbose_name='4. Религиозные отклонения/неопределенность')),
                ('religious_deviations_details', models.TextField(blank=True, verbose_name='Детали')),
                ('suspicious_mobile_content', models.BooleanField(default=False, verbose_name='5. Сомнительный контент на мобильных устройствах')),
                ('suspicious_mobile_details', models.TextField(blank=True, verbose_name='Детали')),
                ('suspicious_behavior', models.BooleanField(default=False, verbose_name='6. Подозрительное поведение (религиозные термины, агрессия)')),
                ('suspicious_behavior_details', models.TextField(blank=True, verbose_name='Детали')),
                ('psychological_issues', models.BooleanField(default=False, verbose_name='7. Психологические отклонения')),
                ('psychological_details', models.TextField(blank=True, verbose_name='Детали')),
                ('relatives_mto', models.BooleanField(default=False, verbose_name='8. Родственники с близкими связями с МТО')),
                ('relatives_mto_details', models.TextField(blank=True, verbose_name='Детали')),
                ('criminal_element', models.BooleanField(default=False, verbose_name='9. Криминально-ориентированный элемент')),
                ('criminal_element_details', models.TextField(blank=True, verbose_name='Детали')),
                ('violence_traces', models.BooleanField(default=False, verbose_name='10. Следы насильственных действий на теле')),
                ('violence_traces_details', models.TextField(blank=True, verbose_name='Детали')),
                ('total_score', models.IntegerField(default=0, verbose_name='Общий балл')),
                ('threat_level', models.CharField(blank=True, max_length=20, verbose_name='Уровень опасности')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='Оценил')),
                ('form_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_assessment', to='platform_manager.formresponse', verbose_name='Ответ на форму')),
            ],
            options={
                'verbose_name': 'Оценка пограничника',
                'verbose_name_plural': 'Оценки пограничника',
                'db_table': 'border_officer_assessments',
            },
        ),
    ]
