# Generated by Django 5.2.7 on 2025-12-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0016_borderofficerassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderofficerassessment',
            name='radical_internet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='assessments/q14/', verbose_name='Фото (вопрос 14)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='full_name_photo',
            field=models.ImageField(blank=True, null=True, upload_to='form_responses/q1/', verbose_name='Фото документа (вопрос 1)'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_full_name',
            field=models.TextField(blank=True, verbose_name='а) укажите ФИО'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_occupation',
            field=models.TextField(blank=True, verbose_name='в) чем занимаются'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='relatives_when_left',
            field=models.TextField(blank=True, verbose_name='б) когда выехали'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visited_duration',
            field=models.TextField(blank=True, verbose_name='б) срок пребывания'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='visited_when_purpose',
            field=models.TextField(blank=True, verbose_name='а) когда и цель поездки'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='last_time_in_homeland',
            field=models.CharField(blank=True, max_length=255, verbose_name='13. Когда в последний раз были на родине'),
        ),
    ]
