# Generated by Django 5.2.7 on 2025-12-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0017_borderofficerassessment_radical_internet_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderofficerassessment',
            name='criminal_element_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы криминала'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='document_issues_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы проблем'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='psychological_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы отклонений'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='radical_internet_content',
            field=models.JSONField(blank=True, default=list, verbose_name='Тип контента'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='radical_internet_sheikhs',
            field=models.JSONField(blank=True, default=list, verbose_name='Радикальные шейхи'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='radical_religious_signs',
            field=models.JSONField(blank=True, default=list, verbose_name='Внешние признаки'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='relatives_mto_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы связей'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='religious_deviations_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы отклонений'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='suspicious_behavior_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы поведения'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='suspicious_mobile_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы контента'),
        ),
        migrations.AddField(
            model_name='borderofficerassessment',
            name='violence_traces_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы следов'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='criminal_element_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='document_issues_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='psychological_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='radical_internet_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='radical_religious_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='relatives_mto_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='religious_deviations_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='suspicious_behavior_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='suspicious_mobile_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
        migrations.AlterField(
            model_name='borderofficerassessment',
            name='violence_traces_details',
            field=models.TextField(blank=True, verbose_name='Дополнительные детали'),
        ),
    ]
