# Generated by Django 5.2.9 on 2025-12-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0018_borderofficerassessment_criminal_element_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borderofficerassessment',
            name='suspicious_mobile_photo',
            field=models.FileField(blank=True, null=True, upload_to='assessments/suspicious_mobile/', verbose_name='Фото подозрительного контента'),
        ),
    ]
