# Generated by Django 5.2.9 on 2025-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0019_borderofficerassessment_suspicious_mobile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='denomination_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='Свой вариант мазхаба'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='denomination',
            field=models.CharField(blank=True, choices=[('hanafi', 'Ханафитский'), ('maliki', 'Маликитский'), ('shafii', 'Шафиитский'), ('hanbali', 'Ханбалитский'), ('ahlu_sunna', 'Ахлю Сунна'), ('other', 'Свой вариант')], max_length=255, verbose_name='Мазхаб/религиозные взгляды'),
        ),
    ]
