# Generated by Django 5.2.9 on 2025-12-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0020_formresponse_denomination_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='person_photo',
            field=models.ImageField(blank=True, null=True, upload_to='form_responses/q1_person/', verbose_name='Фото человека (вопрос 1)'),
        ),
    ]
