# Generated by Django 5.2.9 on 2025-12-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0021_formresponse_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='birth_date',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='birth_place',
            field=models.CharField(blank=True, max_length=500, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='formresponse',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='full_name_and_birth',
            field=models.TextField(blank=True, verbose_name='ФИО, дата и место рождения (старое поле)'),
        ),
    ]
