# Generated by Django 5.2.9 on 2026-02-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_manager', '0022_formresponse_birth_date_formresponse_birth_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='assessments/additional/', verbose_name='Фотография')),
                ('photo_type', models.CharField(choices=[('radical_internet', 'Радикальный контент (вопрос 14)'), ('suspicious_mobile', 'Подозрительный мобильный контент (вопрос 19)')], max_length=50, verbose_name='Тип фотографии')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='platform_manager.borderofficerassessment', verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография оценки',
                'verbose_name_plural': 'Дополнительные фотографии оценки',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FormResponsePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='form_responses/additional/', verbose_name='Фотография')),
                ('photo_type', models.CharField(choices=[('document', 'Документ'), ('person', 'Человек')], max_length=50, verbose_name='Тип фотографии')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('form_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='platform_manager.formresponse', verbose_name='Ответ формы')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография',
                'verbose_name_plural': 'Дополнительные фотографии',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
