# Generated by Django 5.2.7 on 2025-10-19 15:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes_manager', '0001_initial'),
        ('platform_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyReason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requires_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'penalty_reasons',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('requested_start', models.DateTimeField()),
                ('requested_end', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('pickup_location', models.TextField(blank=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bicycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes_manager.bicycle')),
                ('bicycle_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes_manager.bicyclemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('terms', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('scheduled_end_at', models.DateTimeField()),
                ('actual_end_at', models.DateTimeField(blank=True, null=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('archived', models.BooleanField(default=False)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes_manager.bicycle')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.booking')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rentals',
            },
        ),
        migrations.CreateModel(
            name='RentalArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent_manager.rental')),
            ],
            options={
                'db_table': 'rental_archive',
            },
        ),
        migrations.CreateModel(
            name='RentalEndReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition_notes', models.TextField(blank=True)),
                ('rating', models.SmallIntegerField(default=5)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_manager.adminuser')),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_report', to='rent_manager.rental')),
            ],
            options={
                'db_table': 'rental_end_reports',
            },
        ),
        migrations.CreateModel(
            name='ReportPenalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('penalty_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_manager.penaltyreason')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='rent_manager.rentalendreport')),
            ],
            options={
                'db_table': 'report_penalties',
            },
        ),
        migrations.CreateModel(
            name='ReportPenaltyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rent_manager.reportpenalty')),
            ],
            options={
                'db_table': 'report_penalty_photos',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KZT', max_length=8)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=16)),
                ('payment_provider', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.booking')),
                ('rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_url', models.TextField(blank=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rent_manager.transaction')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_status_1ef630_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_active_contract_per_user'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('payment_provider', 'provider_reference'), name='unique_provider_reference'),
        ),
    ]
