# Generated by Django 5.2.7 on 2025-10-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='invoice',
            name='data_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rentalarchive',
            name='payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='rentalendreport',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
