# Generated by Django 5.2.7 on 2025-10-22 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes_manager', '0002_alter_bicycle_options_alter_bicyclemodel_options_and_more'),
        ('platform_manager', '0006_alter_adminuser_options_alter_eventlog_options_and_more'),
        ('rent_manager', '0002_booking_metadata_invoice_data_json_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalarchive',
            name='rental',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Бронирование'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Чек об оплате', 'verbose_name_plural': 'Чеки об оплатах'},
        ),
        migrations.AlterModelOptions(
            name='penaltyreason',
            options={'verbose_name': 'Причина штрафа', 'verbose_name_plural': 'Причины штрафов'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterModelOptions(
            name='rentalendreport',
            options={'verbose_name': 'Отчёт об окончании аренды', 'verbose_name_plural': 'Отчёты окончания аренды'},
        ),
        migrations.AlterModelOptions(
            name='reportpenalty',
            options={'verbose_name': 'Отчёт штрафа', 'verbose_name_plural': 'Отчёты штрафов'},
        ),
        migrations.AlterModelOptions(
            name='reportpenaltyphoto',
            options={'verbose_name': 'Фото штрафа', 'verbose_name_plural': 'Фотографии штрафов'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RemoveConstraint(
            model_name='contract',
            name='unique_active_contract_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_provider_reference',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_status_1ef630_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='active',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='penaltyreason',
            name='code',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_number',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='rentalendreport',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='rentalendreport',
            name='penalty_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_provider',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='provider_reference',
        ),
        migrations.AddField(
            model_name='booking',
            name='manager_comment_text',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_comment_text',
            field=models.TextField(blank=True, editable=False, verbose_name='Комментарий пользователя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bicycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes_manager.bicycle', verbose_name='Велосипед'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bicycle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes_manager.bicyclemodel', verbose_name='Модель велосипеда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requested_end',
            field=models.DateTimeField(verbose_name='Дата окончания брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requested_start',
            field=models.DateTimeField(verbose_name='Дата начала брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('CONFIRMED', 'Обработано'), ('CANCELLED', 'Отменено'), ('EXPIRED', 'Истекло'), ('CLOSED', 'Закрыто')], default='PENDING', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(max_length=64, unique=True, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Дата вступления в силу'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Не подписан'), ('ACTIVE', 'Подписан'), ('CANCELLED', 'Расторгнут')], default='DRAFT', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='data_json',
            field=models.JSONField(default=dict, verbose_name='Данные чека'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='номер чека'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.TextField(blank=True, verbose_name='Ссылка на чек'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='rent_manager.transaction', verbose_name='Транзакция'),
        ),
        migrations.AlterField(
            model_name='penaltyreason',
            name='default_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа'),
        ),
        migrations.AlterField(
            model_name='penaltyreason',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='penaltyreason',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='penaltyreason',
            name='requires_photo',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='penaltyreason',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='actual_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата окончания аренды'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='bicycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes_manager.bicycle', verbose_name='Велосипед'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.contract', verbose_name='Договор'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма депозита'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления о просрочке'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='overdue_reason',
            field=models.TextField(blank=True, verbose_name='Причина просрочки'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма удержания'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='scheduled_end_at',
            field=models.DateTimeField(verbose_name='Дата запланированного окончания аренды'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_at',
            field=models.DateTimeField(verbose_name='Дата начала аренды'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Создана'), ('ACTIVE', 'Активно'), ('COMPLETED', 'Завершено'), ('OVERDUE', 'Просрочено'), ('CANCELLED', 'Отменено')], default='INITIATED', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='condition_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_manager.adminuser', verbose_name='Ответственный менеджер'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='rating',
            field=models.SmallIntegerField(default=5, verbose_name='Рейтинг состояния велосипеда (1-5)'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='rental',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_report', to='rent_manager.rental', verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='rentalendreport',
            name='resolved',
            field=models.BooleanField(default=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='KZT', editable=False, max_length=8, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rent_manager.rental', verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', editable=False, max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('REFUND', 'Refund'), ('DEPOSIT', 'Deposit'), ('PENALTY', 'Penalty')], editable=False, max_length=16, verbose_name='Тип транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.DeleteModel(
            name='RentalArchive',
        ),
    ]
